### ISSUE TITLE
bring user to login (page) when clicking on a registered dataset while no logged-in

### ISSUE THREAD

**Issue by PapillonMcGill** [CONP-PCNO/conp-portal#113]
## Purpose
To help in usability of the portal, and remind user that a dataset need registered access instead of letting them think it is just not available for some (unknown) reason.

## Context
users that are not logged-in can still see registered datasets but the icon to download is grayed out and unclickable.

**Comment by xlecours** [comment]
@PapillonMcGill is there a dataset with "registered access"?

**Comment by PapillonMcGill** [comment]
@xlecours Not to my knowledge.

**Comment by glatard** [comment]
isn't PreventAD registered access?

**Comment by PapillonMcGill** [comment]
The one currrently on CONP-dataset is open. There is plan to put a restricted version with more data but it is not yet there.

**Comment by xlecours** [comment]
We got a confirmation from @jbpoline that PREVENT-AD would agree to grant access to any user that can authenticate with ORCID. 

Not quite sure how to handle that. 

Option 1 (server side). since the access policy is a per resource server limitation, te resource server (LORIS in this case) should handle their policy; OAuth via ORCID. We sould need to change the datalad provider in the datatset from loris-token to ?? OAuth ??

Option 2 (delegation token). have the conp-portal enable the ORCID login feature and ask the resource server to provide a username and password fro the portal to generate a JWT token that will be passed to the user. The datalad provider should now accept the given token instead of prompting for username and password. Since datalad used `keyring` to store the tokens for provider such as loris-token, can we use `keyring` to store the token before datalad ask for it?

Option 3 (?): open to suggestions
