### ISSUE TITLE
Link to instructions for data upload is broken

### ISSUE THREAD

**Issue by glatard** [CONP-PCNO/conp-portal#152]
Link to instructions for data upload, referenced at https://portal.conp.ca/share, is broken.

## Expected Behavior
Link should refer to a page explaining how to upload data, using DataLad directly or through Zenodo. 

Suggested page: https://github.com/CONP-PCNO/conp-dataset/blob/master/.github/CONTRIBUTING.md

## Current Behavior

Link points to https://portal.conp.ca/datalad_dataset_addition_procedure.md, which is broken.

Note: I'm also not sure why the information about DATS fields is duplicated on the portal while it's already present in https://github.com/CONP-PCNO/conp-dataset/blob/master/.github/CONTRIBUTING.md I'd suggest just pointing https://portal.conp.ca/share to https://github.com/CONP-PCNO/conp-dataset/blob/master/.github/CONTRIBUTING.md, to avoid duplication of information.

**Comment by emmetaobrien** [comment]
I have just submitted https://github.com/CONP-PCNO/conp-documentation/pull/8 which fixes these links.

**Comment by xlecours** [comment]
@emmetaobrien I am not opposed to link to conp-dataset/CONTRIBUTING.md instead of having to manage 2 location for the contribution instructions. Do you see benefits in having the conp-documentation repo in addition to dataset contribution instructions? 
I think we can keep the https://github.com/CONP-PCNO/conp-portal/blob/master/app/templates/share.html page but rearrange it's content to link to CONTIBUTING.md for more details. 
What do you think?

**Comment by xlecours** [comment]
I had to send https://github.com/CONP-PCNO/conp-portal/pull/157 to fix the portal version of that file
