### ISSUE TITLE
Download instructions on individual dataset page problems

### ISSUE THREAD

**Issue by emmetaobrien** [CONP-PCNO/conp-portal#187]
Testing the download commands on the pages for each individual dataset has shown that they are at best unclear and easily do not work.  I propose replacing the text under the line 

`# Here are commands to download content from this dataset`

with something along the lines of

`datalad install -r <name of dataset repository>`
`cd <name of dataset repository>`
`datalad get <files of interest>`

Is there also a potential failure mode of installing http://github.com/CONP-PCNO/conp-dataset, as the current instructions specify, if people can then do a 
`datalad get conp-dataset/projects/<name of dataset repository>`  
for a dataset that is not fully open without going through the portal?

**Comment by glatard** [comment]
Updates in the instructions sound good, as long as they are tested and work well. 

There is no problem installing the DataLad dataset for datasets with restricted access, as the hosting platforms enforce authentication.

**Comment by emmetaobrien** [comment]
That prevents people from downloading the content of links; I was just wondering whether there might be an issue with unauthorised download of dataset directory structures, or unannexed small files (such as text summaries of data) that will be stored directly in the repository and could be retrieved without linking to the host platform.

**Comment by xlecours** [comment]
I can see a potential issue with the recursive installation of all datasets. Whit just a few datasets we are still under 1 minute but it could take a few minuets when we have many more than 50 datasets. This is the reason why I have split the the install process in 2.

**Comment by glatard** [comment]
Suggested revised instructions, including installation of the main dataset (not recursively):
`
datalad install https://github.com/CONP-PCNO/conp-dataset.git
cd conp-dataset
datalad install projects/<dataset_dir>
datalad get <file_name>
`

**Comment by cmadjar** [comment]
FYI - just tested the instructions that @glatard posted and works like a charm!

**Comment by yarikoptic** [comment]
I want to echo @glatard and think instructions should be improved further -- you might also would like to provide the dataset specific (not going through super-dataset) commands.  ATM they seems to be erroneous in two aspects: looking at https://portal.conp.ca/dataset?id=projects/bigbrain-datalad current instructions are:
```
    ~$ datalad install --source http://github.com/CONP-PCNO/conp-dataset
    ~$ datalad get --no-data conp-dataset/projects/bigbrain-datalad
    ~$ cd conp-dataset/projects/bigbrain-datalad
```

1. unfortunately `datalad get` command wouldn't work with `datalad >= 0.12` as is.  That one requires to cd to the (super)dataset and issue the get or install command, e.g.

`cd conp-dataset ; datalad get --no-data projects/bigbrain-datalad`

That is what @glatard changed instructions fix

2. There is no `projects/bigbrain-datalad` path there -- there is `projects/BigBrain`.  It seems that submodules configured with a name different from the path
```
[submodule "projects/bigbrain-datalad"]
	path = projects/BigBrain
	url = https://github.com/conpdatasets/bigbrain-datalad.git
```
which is the reason.

But let me get back to the original issue of installing super-dataset first...  Ideally for an individual dataset it should just be a straight 
```
datalad install https://github.com/conpdatasets/bigbrain-datalad.git
```
Although installing superdataset opens easy access to other subdatasets, IMHO it might be suboptimal because

1. there is really no need for superdataset installation to get the most recent version of the dataset (installing superdataset could actually prevent installing most recent version if superdataset points to some older release)
2. updates of the superdataset recursively would update all subdatasets, which might be undesired.

I think "go through superdataset" should be mentioned as another alternative way (possibly on a dedicated page, pointed to by individual datasets pages) and possible benefits/use cases outlined

- quick expoloration (`install`/`uninstall` `path`)
- search for datasets
- use of CONP-PCNO "vetted" version

**Comment by jbpoline** [comment]
Thanks @yarikoptic !
Also, Instructions for installation should point to the DL handbook : this is the place where install documentation is most likely to be updated

**Comment by cmadjar** [comment]
@jbpoline about the instructions on how to install datalad, this PR was merged yesterday so that we point to the DataLad handbook: https://github.com/CONP-PCNO/conp-documentation/pull/18

@yarikoptic I went through most of the handbook, congrats on the amazing documentation!!! Makes it easy to understand how DataLad works :).

**Comment by xlecours** [comment]
https://github.com/CONP-PCNO/conp-portal/blob/master/app/templates/dataset.html#L60

**Comment by xlecours** [comment]
PR Sent

**Comment by cmadjar** [comment]
Thank you @xlecours. Closing the issue since the instructions have been updated on the portal
