### ISSUE TITLE
Add json-ld descritors on the portal web page(s)

### ISSUE THREAD

**Issue by xlecours** [CONP-PCNO/conp-portal#301]
## Purpose
Provide json-ld descriptors for indexers (bots) to crawl the portal pages and know what the website is about.

## Context
https://github.com/CONP-PCNO/conp-portal/pull/195

## Possible Implementation (optional)
The schema.org json-ld should be added here, e.g.:
```
<html>
  <head>
    <title>Test dataset</title>
    <script type="application/ld+json">
    {
      "@context":"https://schema.org/",
      "@type":"Dataset",
      ......
    }
    </script>
  </head>
  <body>
  </body>
</html>
```
Some research need to be done on best practices but here is my naive implementation suggestion:
1. Add the descriptors in the detail page of each dataset.
2. Add an aggregated jons-ld in the search page
3. Provide a sitemap on portal.conp.ca landing page to help the indexers.

**Comment by jbpoline** [comment]
@emmetaobrien @liamocn  @zxenia : I thought we already had this to be discoverable by google datasets ?

**Comment by emmetaobrien** [comment]
I believe @xlecours has developed this, but I am not sure whether it is currently active.

**Comment by zxenia** [comment]
The code is there for serving google json-ld but the generated json-ld snippet should be added to frontend.

**Comment by xlecours** [comment]
@zxenia Is right. And she did the development :)

**Comment by zxenia** [comment]
Hi @liamocn 

Here is how the schema.org json-ld should be added to the front-end. I don't know the conp-portal codebase well so this solution is approximate.

Class DATSDataset (app\search\models.py) has a property `schema_org_metadata` which returns json-ld required by Google Dataset search.

1. In `app/search/routes.py` https://github.com/CONP-PCNO/conp-portal/blob/master/app/search/routes.py#L319

function `dataset_info()` should also include `schema_org_metadata` value (or another option would be adding to `get_dataset_metadata_information()`)
e.g.
```
dataset = {
    "schema_org_metadata": datsdataset.schema_org_metadata,       # add this
    "authorized": authorized,
    "name": datsdataset.name,
    ... etc.
}
```

2. In `app/templates/dataset.html`

I think it can be added to the block scripts since it has to be placed inside of the `<head>` tag:

`<script type="application/ld+json">{{ data.schema_org_metadata }}</script>`


When we go to an individual dataset webpage we should see in the `<head>` something like e.g.:

```
<head>
    <script type="application/ld+json">
    {
      "@context":"https://schema.org/",
      "@type":"Dataset",
      "name": "Braincode....",
      ......
    }
    </script>
</head>
```

After it's in the portal it might take a few days for Google to crawl the metadata in order to be added to the Google Dataset search.

**Comment by cmadjar** [comment]
@zxenia  @liamocn can you confirm that this is resolved and live on the portal? I tried to look for our datasets in Google dataset search but could not find them.

**Comment by liamocn** [comment]
@cmadjar The code change is live on the portal as I can see the updated head tags. I'm not sure how long it typically takes for Google to crawl the new pages or if there are other optimizations we can make.

**Comment by zxenia** [comment]
@cmadjar @liamocn It might take some days to get into google datasets search.

But I think there is another issue: if I test the dataset page in Google rich results I get an error that markup is not correct. So I changed singe quotes in json-ld for double and it passes the validation. 
I checked a few datasets and seems like it inconsistently renders single and doubles quotes:

<pre>{'@context': 'https://schema.org/', '@type': 'Dataset', 'name': 'PREVENT-AD open data', 'description': <b>"Longitudinal study of pre-symptomatic Alzheimer's Disease"</b>, 'version': '2.0', 'license': ['https://openpreventad.loris.ca/images/Open_PREVENT-AD_Terms_of_Use.png'], 'keywords': ['Prevention', "Alzheimer's disease", 'Structural MRI', 'Functional MRI', 'Longitudinal'], 'creator': [{'@type': 'Organization', 'name': 'StoP-AD Center - Douglas Mental Health University Institute'}]}</pre>

Maybe we can try `|tojson`  instead of `|safe`  in template.

**Comment by liamocn** [comment]
@zxenia @cmadjar Yes, it seems like tojson is the correct filter in this case. I've just tried it and everything gets double quotes

`{"@context": "https://schema.org/", "@type": "Dataset", "creator": [{"@type": "Organization", "name": "StoP-AD Center - Douglas Mental Health University Institute"}], "description": "Longitudinal study of pre-symptomatic Alzheimer\u0027s Disease", "keywords": ["Prevention", "Alzheimer\u0027s disease", "Structural MRI", "Functional MRI", "Longitudinal"], "license": ["https://openpreventad.loris.ca/images/Open_PREVENT-AD_Terms_of_Use.png"], "name": "PREVENT-AD open data", "version": "2.0"}`

**Comment by cmadjar** [comment]
@zxenia @liamocn Thank you for the fix `tojson`! I tried this morning searching for some CONP dataset in Google search and could not find them. Any other ideas?

**Comment by zxenia** [comment]
@cmadjar let's wait first because it takes several days for google to find and crawl it

**Comment by cmadjar** [comment]
@zxenia I just checked after the call and I see only two CONP datasets in google dataset search that appears now. BigBrain and preventad-open.

Do you know why? Could this be related to the fact that the JSON-LD fields were removed from the DATS.json of most dataset? Should they be added back?

**Comment by emmetaobrien** [comment]
The schema.org descriptors google looks for in dataset search, attached to the webpages the dataset is on, are a distinct thing separate from the dataset metadata in DATS.json, so I don't see how there could be any connection.

**Comment by zxenia** [comment]
@emmetaobrien @cmadjar my guess now is that only those datasets' webpages were indexed by google crawlers so far, the rest will be added too when google bots find them.

**Comment by zxenia** [comment]
@cmadjar 
> Could this be related to the fact that the JSON-LD fields were removed from the DATS.json of most dataset?

the json-ld for google is generated from DATS.json info (it doesn't rely on those removed json-ld fields)  and only uses the required fields so this should not be an issue

**Comment by cmadjar** [comment]
Datasets are (very) slowly being added to Google Dataset Search so I guess we can close this issue.

@zxenia feel free to reopen if you do not agree.
