### ISSUE TITLE
Create a community server to offer for data upload for users that do not have a server to host their data

### ISSUE THREAD

**Issue by cmadjar** [CONP-PCNO/conp-portal#302]
## Purpose

Creation of a centralized server where people who don't have dedicated space would upload there their data. That would be a CBRAIN data provider with DataLad.

Idea in Samir's head.

@xlecours Samir says you know what he wants so could you take the lead on this item and set up the server and data provider that would be accessible for CONP and NeuroHub. Feel free to update the ticket with proper description after having talked with Samir about what he wants.

Timeline would be end of July 2020 for this.

**Comment by glatard** [comment]
Hi @cmadjar, could we discuss this at our next dev meeting? I have a few thoughts on this but am missing context (putting them here so that I dont forget them :) ):
* I guess the goal is to streamline processing but am not sure if you really meant using CBRAIN as a storage solution.
* There are currently two issues with CBRAIN's datalad dataprovider: (1) it doesn't support authentication, (2) the handling of sub-directories in CBRAIN is a bit convoluted. This might require some development there too.
* To upload public data, OSF and Zenodo might be easier to use, more sustainable, and they are already available in CONP.

**Comment by xlecours** [comment]
@glatard To my understanding, this issue is about:

1) Allow processing of CONP dataset from CBRAIN.  
As you said CBRAIN datalad dataprovider have limited functionalities at the moment but they could still be used for open datasets that don't have subdatasets. 

2) Provide storage location for datasets/projects that can't guaranty persistency or accessibility of resources servers. We already did that for Simon's phantoms dataset on an MCIN server. (Speculation follows!) I think this could be something that NeuroHub could maintain.

**Comment by cmadjar** [comment]
Discussed at the CONP dev meeting of July 2nd 2020:
- The goal of that server would be to give an option to those who do not have space to use a common space to upload their data
- OSF and Zenodo allows for upload of large dataset so we could delay the creation of a community server
- Deadline pushed to September

@xlecours feel free to add anything I might have missed during the discussion of that topic. Thanks!

**Comment by cmadjar** [comment]
Discussed on October 19th, 2020.

Goal: have a place where people could upload their open datasets. Then add the authentication feature

- Amnesia SFTP server - not much space on that server but could mount extra storage on it (20TB to start).
- Will need to specify a policy for a limit of 50GB upload and contact us if need more.
- Write a crawler to crawl the new data on the SFTP server that would send a PR to conp-dataset with the DATS.json and README.md files
- Emmet will be facilitating the upload of datasets on the SFTP server. (conp-admin account on a sftp.conp.ca)
- Once we have authentication, for the up to 50GB, we will allow users to request accounts to upload data but that will come later

The server should be ready is about a week.

**Comment by cmadjar** [comment]
Redmine issue created for the sys admin: https://redmine.cbrain.mcgill.ca/issues/18451

**Comment by emmetaobrien** [comment]
As of today, the first dataset to be hosted on the community server has gone live, in https://github.com/CONP-PCNO/conp-dataset/pull/479.  I think the tack of creating that server can now reasonably be marked as closed.
