### ISSUE TITLE
Improved listing of CBRAIN pipelines in the portal

### ISSUE THREAD

**Issue by glatard** [CONP-PCNO/conp-portal#378]
## Purpose

Currently, several CONP pipelines are installed in CBRAIN but do not appear as such in the portal.

## Context

This feature will facilitate the listing of CBRAIN pipelines in CONP.

## Possible Implementation

1. Create a JSON object in the portal, with the following schema:
```
{
'zenodo_id': 'CBRAIN URL'
}
```
The CBRAIN URL should be the link of the launch task in CBRAIN. See https://github.com/aces/cbrain/pull/1047. Example: https://portal.cbrain.mcgill.ca/userfiles?prepare_tool_id=XX. See message from @natacha-beck in #347. 

For instance:
```
{
    "zenodo.1450999": "https://portal.cbrain.mcgill.ca/userfiles?prepare_tool_id=73",
    ...
}
```

This object should be stored in a JSON file available in the GitHub repository of the portal.

2. Update the pipelines page in the portal (https://portal.conp.ca/pipelines) such that pipelines with a cbrain URL appear with the blue CBRAIN icon linking to this URL.

For instance, a pipeline with a CBRAIN URL will appear as follows:
![Screenshot from 2020-11-26 13-42-39](https://user-images.githubusercontent.com/5174953/100384102-5719df00-2fed-11eb-8143-c5eafe012fb9.png)
(see blue CBRAIN icon with link)

while a pipeline without a CBRAIN URL will appear as:
![Screenshot from 2020-11-26 13-43-31](https://user-images.githubusercontent.com/5174953/100384120-6567fb00-2fed-11eb-9c01-d81bd521bb58.png)
(see grey CBRAIN icon)

## Related issues

#347, @natacha-beck could answer CBRAIN-related questions, @liamocn could answer CONP portal questions.

**Comment by liamocn** [comment]
@glatard We used to have all the information about running the pipelines ( on CBRAIN and other platforms ) in the boutiques descriptors. Is that not the case anymore?

**Comment by cmadjar** [comment]
@liamocn I think the idea is to not rely anymore strictly on the Boutiques descriptor since it is complicated to track down the owner of the descriptor and ask them to update their boutiques descriptor to add a link to CBRAIN.

If we store that information ourselves in a JSON file, we can then update ourselves the CBRAIN links whenever tools are available on CBRAIN. It will need to be a manual process to update that list but it should not be too time demanding.

Does that make sense?
