### ISSUE TITLE
Beta Release Specs

### ISSUE THREAD

**Issue by paiva** [CONP-PCNO/conp-portal#46]
Need to write the roadmap and beta release specs. Plan to open between July and August

**Comment by shots47s** [comment]
The Beta Specs for the platform should include (open for discussion):

1) The web-platform hosted on a VM within the MCIN network.
2) The Data entries being dynamically populated through datalad or similar mechanism (right now they are statically defined).
3) Data entries should dynamically updated statistics as people download or view the entries.
4) All datasets available should either be directly downloadable from the platform, or point to somewhere where the user can get the dataset (LORIS, BrainCode, etc.)
5) ORCID authentication should work so that users can log in with their orcid ids.
6) Pipelines page should be more presentable with functioning launching options to CBRAIN or CMD.
7) Role based authentication should be implemented and working, with an admin interface for manipulating existing users.

I have started a 0.9 milestone that we can target with these, once this is definitive, we will start working on these items in earnest.

Comments welcome.

**Comment by xlecours** [comment]
1. done.
2. done.
3. not done, downlaod is not happening through the portal. views can be captured. (to revisit when an analytics framework is add.)
4. done. Added access.landingPage for source in the DATS file.
5. Will be revisited once we have a restricted access dataset.
6. That is a desired feature. (we are not there yet)
7. It might be the case already. But we don't use that feature yet.

**Comment by xlecours** [comment]
Closing this. Specific issues will be created for each desired feature.
