### ISSUE TITLE
Setting up VM webserver

### ISSUE THREAD

**Issue by DESm1th** [CONP-PCNO/conp-portal#69]
## Purpose
The conp-portal VM needs a production capable web server set up and running. Currently this does not seem to be configured correctly.

## Possible Implementation 
I will:

- [ ] Set up NGINX+ uWSGI for the flask app
- [ ] Configure the firewall / fail2ban / alerts emailed to admins for security
- [ ] Set up letsencrypt https certs for the portal.conp.ca domain + set up auto-renewal of certs (unless you already have certs available, please let me know) 
- [ ] Ensure DNS is set up to allow the portal.conp.ca domain to be accessed by end users (this does not appear to be in place yet, but please let me know if you guys already have something ready to roll out)
- [ ] Write an Ansible playbook to document the correct configuration and allow the VM to be re-provisioned from scratch (If a configuration management package other than Ansible is already in use by the project let me know and I'll use that instead)

@shots47s , @glatard : Thoughts?

**Comment by shots47s** [comment]
By assigning me this, are you saying that I am responsible for doing this or will you be doing this?

**Comment by DESm1th** [comment]
Oh sorry! I'd be doing this, JB just asked me to ping you and tristan and
so i just assigned you without thinking ha. Sorry.

**Comment by shots47s** [comment]
No problem, if you run into any barriers, please do not hesitate to ask.

**Comment by shots47s** [comment]
These steps sound good, we have some system admins that can help with these items, and many may aleady be set up. I will send an email connecting you to them.

**Comment by shots47s** [comment]
I have created an MCIN ticket and asked that one of the systems engineers come on here and help with this.  Since this will likely be housed within our ecosystem as a VM, we need to make sure they are involved and that the machine properly sits inside with the appropriate firewalling and monitoring.

**Comment by DESm1th** [comment]
I think Santi has gotten at least partway through that setup. A VM exists
which he gave me access to, but its public DNS records dont seem to be set
up, and the webserver isnt up and running.

**Comment by shots47s** [comment]
According to our systems folks, it is currently set up as dev VM, so I need to talk to them about what the best way forward is, I will do so shortly and post results here. What is the definitive name we want for the DNS, 'portal.conp.ca'?

**Comment by shots47s** [comment]
One missing component, we need to setup backups for the database.

Also, we should think about a 'dev' and a 'production' environment.  There are few options:

Option 1: We could make these separate servers with separate databases.
1. Advantages:
a. Completely separate environments so that they can't trample on each other.
2. Disadvantages:
a. Two separate VMs to deploy and maintain

Option 2: We could make these separate servers sharing the same remote database.
1. Advantages:
a. We could test the dev environment with the same data as the production environment
2. Disadvantages:
a. Two separate VMs to deploy and maintain
b. Potential that a dev deployment could destroy the database, which is why backups are critical (well they are critical for making sure the production environment is good too)

Option 3: We could put the dev and production servers on the same machine and have them share either a remote database or a local database
1. Advantages:
a. One machine to maintain, easy to replicate all of the services across two machines for redundancy
b. Database in one place
2. Disadvantages:
a. if it goes down, we need to switch to a new machine
b. database can still get trampled on.

We should also think about how one will develop for the portal outside of deployments, for this we can set up a DockerFile or clear instructions on a local build environment.

Thoughts?

**Comment by shots47s** [comment]
Ok, have talked this over with the systems team.  

You will not need to do steps 2,3, and 4, our infrastructure is already set up to do this.

Step 1: will be to change the current VM of conp.portal.ca to conp.portal-dev.ca to clearly delineate that it is not a production environment as of yet.
Step 2: set the VM up to use our LDAP system so that we have secured and full control over the people that can log into it.  Having VM's using a common account is not secured or desirable, because we have no way to know who is logging into the machine.  I will create a separate issue for this.
Step 3: @DESm1th will need sudo on this VM so that Flask, NGINX, and uWSGI can be installed and set up as a valid webserver.  (again do not worry about firewalling, secure certs, dns, we can set all of this up).
Step 4: We need to confirm that the platform can use MySQL, if so, we already have both a production and dev databasing environment with backups enabled that we can take advantage of.  We can then just point to it in our Flask configuration.

@andytengca has been added to this team to be able to help us work through these issues. 

Any issues with this plan?

**Comment by DESm1th** [comment]
Sounds good to me! The platform is using sqlalchemy so it should be fine with mysql with few / no changes required (I might just need to change the connection string and add package to the requirements list).

**Comment by shots47s** [comment]
Agreed on all fronts, we want to make sure that people can develop separate from the production setup.

**Comment by andytengca** [comment]
I've changed the DNS hostname for dev VMs

dev hostname is portal-dev.conp.ca

I will turn dev vm into ldap system and create a ldap group to limit the users to login either dev vm or pro vm.

Please list a group of users who need to access to these vms, thanks.

Andy

On 2019-08-12 2:02 p.m., Dawn E. Smith wrote:

Sounds good to me! The platform is using sqlalchemy so it should be fine with mysql with few / no changes required (I might just need to change the connection string and add package to the requirements list).

**Comment by cmadjar** [comment]
@glatard It feels like this should be closed so I am closing it. Feel free to reopen if I am misreading this?
