### ISSUE TITLE
Should updating pipelines add data to the database or should we rely on the file based search that is there now?

### ISSUE THREAD

**Issue by shots47s** [CONP-PCNO/conp-portal#95]
## Purpose
The updating of pipelines data from Zenodo happens at add places in the portal workflow by spawning threads.  These leads to inconsistent datasets, and the file based nature of this seems a bit fragile.

## Context
Should we have all of the data for the portal translated to the database, so that we have models to manipulate or is it best to rely on the cache files that are occurring now?  The database may be easier to index with something like elastic search.

## Possible Implementation (optional)
rewrite the system so that updating the pipeline data modifies the records in the database rather than being created on the fly from files in a .boutiques directory.

**Comment by glatard** [comment]
`bosh` pulls descriptors in `.boutiques` and this won't be changed. The portal-specific file could be added to the database indeed, if this file becomes an issue. There shouldn't be any concurrent access to the file though.

**Comment by driusan** [comment]
PR#105 and #103 fix the "spawning threads in odd places" issue and #104 fixes a (much more important) bug where the pipelines page was showing datasets instead of pipelines.

I'm not convinced that it's worth putting the data in the database instead of sharing the `~/.cache/boutiques` directory with bosh. There's currently an (unused) Pipeline database model defined in `app/models.py`, but the format of it doesn't match the bosh descriptors and I'm not convinced the file I/O is a significant bottleneck.
